
* Q1. List up to four keywords/key phrases from your paper from the following list: 

search
planning


* Q2. Please state in no more than 150 words why your work is important to other researchers in Artificial Intelligence and how they could make use of your results.

This paper investigates and improves the tie-breaking strategies for A* in depth. To our knowledge, such an
in-depth analysis is lacking in the literature. We break some conventional wisdoms regarding tiebreaking for
A* and propose several improvements. Since A* is a standard algorithm for cost-optimal search, our
contribution advances the state-of-the-art and benefits many applications.

In particular, we focus on a particular type of problems with a clear objective function e.g. resource,
preference etc., which models the more realistic optimization problems. We show that these problems pose a
challenge to the existing tiebreaking strategies and our method outperforms the existing ones.

* Q3. Please list 1 - 3 papers previously published in JAIR that are closest to your work,  

# and explain in no more than 150 words how your work differs from those papers.
# If you consider no previous articles in JAIR to be sufficiently close to your work,
# please state this and instead list a previous JAIR publication that has a similar structure to your submission.
# Please note that articles with little similarity in content or structure to published JAIR articles
# have a high chance of rejection without review.

Hoffmann, J. (2005). Where ’Ignoring Delete Lists’ Works: Local Search Topology in Planning
Benchmarks. J. Artif. Intell. Res.(JAIR), 24, 685–758.

This paper analyzes the search space structure of various individual planning domains in the context of local
search. Our paper, in contrast, addresses the specific problem that arise in the cost-optimal planning and is
more focused on the search algorithm improvement.

Goldenberg, Meir, et al. "Enhanced Partial Expansion A*." J. Artif. Intell. Res.(JAIR) 50 (2014): 141-187.

This is a paper on EPEA*, an enhancement to A* algorithm for cost-optimal search.
EPEA* trades the runtime for the number of node generation (memory usage) by allowing re-expansion of nodes.
Tiebreaking strategy is orthogonal from this modification.


* Q4. If any part of this paper has been previously published, please state where and explain how the current paper differs. If you answer positively, please state where and explain how the current paper differs.

This paper is a significantly extended version of the AAAI-16 paper by the same authors. The addition to the
conference paper is the following:

1. Introduction of deterministic depth-based diversification strategy (as opposed to the randomized version in
   the conference paper), and its theoretical analysis in Section 6.  We also added thorough empirical
   analysis in Section 7 that are not included in the conference version.

2. Empirical analysis of distance-to-go estimates in Section 8. Also, we included an empirical evaluation of
   the use of inadmissible FF heuristics as part of tiebreaking criterion, and its combination with the depths
   metric thereof.
3. New perspective to A∗ and the preliminary results on the use of depth for satisficing search (Section 9).


* abstract

In this paper, we investigate and improve tiebreaking strategies for cost-optimal search using A*. We first experimentally analyze the performance of common tiebreaking strategies that break ties according to the heuristic value of the nodes. We find that tiebreaking strategy has a significant impact on search algorithm performance when there are zero-cost operators that induce large plateau regions in the search space. With this in mind, we develop two new kinds of tiebreaking strategy. The first one is based on a depth metric which measures the distance from the entrance to the plateau and proposes a new, diversifying strategy which significantly outperforms standard strategies on domains with zero-cost actions. We give both a theoretical analysis and an empirical analysis supporting this. Another one is an admissible multi-heuristic tiebreaking strategy based on the inadmissible distance-to-go variations of various heuristics. It is shown to further improve the performance in combination with the depth metric. Finally, we open a new interpretation to the cost-optimal search by pointing out that the multi-heuristic strategy is a rare attempt to apply a satisficing technique to cost-optimal search. This new interpretation is additionally supported by the empirical results of the satisficing search using GBFS enhanced by the depth diversification.  Note to Reviewers: This paper is a significantly extended version of the AAAI-16 paper by the same authors. Additions are summarized at the end of Section 1.
